[package]
name = "sailce_path_crypto"
version.workspace = true
description = "Encryption and decryption of the paths of Willow."
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
#TODO? categories.workspace = true
#TODO? keywords.workspace = true

[features]
default = ["alloc"]
alloc = []

[dependencies]
sailce_data_model.workspace = true

[lints]
workspace = true
