edition = "2021"
fn_params_layout = "Vertical"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
max_width = 98
reorder_modules = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

unstable_features = true
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
control_brace_style = "ClosingNextLine"
combine_control_expr = false
comment_width = 98
enum_discrim_align_threshold = 60
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
format_macro_matchers = true
group_imports = "StdExternalCrate"  # Ineffective with imports_granularity="One"
imports_granularity = "One"
imports_layout = "Vertical"
match_arm_blocks = false
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
# report_fixme = "Unnumbered"  # Don't want for every random file, but can be desirable at times.
# report_todo = "Unnumbered"   # Don't want for every random file, but can be desirable at times.
spaces_around_ranges = true
struct_field_align_threshold = 40
version = "Two"
where_single_line = true
wrap_comments = true
